# config.py
EVENT_NAME = "SISHEN BORGDAG"
DEFAULT_RINKS = 7
DEFAULT_ROUNDS = 6
DEFAULT_SECTIONS = ["SEKSIE 1", "SEKSIE 2"]

# default scoring rules
POINTS_WIN = 2
POINTS_DRAW = 1
POINTS_LOSS = 0
BONUS_ENABLED = False
BONUS_THRESHOLD = 10
BONUS_POINTS = 1
